### ISSUE TITLE
using nuller and joiner

### ISSUE THREAD

**Issue by seiyria** [kach/nearley#97] opened 2016-05-14 03:35 UTC
Seen [here](https://github.com/Hardmath123/nearley/blob/b3296b31864f60b26237fddae522d18cac7cadc0/lib/generate.js#L118-L123), but if I do something like... `_ -> [\s]:* {% nuller %}` it doesn't work - it says nuller is not defined. I see that you spit out `id` into the generated code, but not joiner, nuller, or arrconcat. How do you use them?

**Comment by Hardmath123** [comment] 2016-05-14 03:48
Ah, interesting, someone must have slipped those guys in with the coffeescript integration. You should just include the definitions in `{% %}`s and move on with writing your grammar. When I have time, I'll figure out what those weird definitions are doing. :-)

**Comment by seiyria** [comment] 2016-05-14 03:50
Hehe. Yeah, so all I did was::

```
@{% function nuller() { return null; } %}
@{% function joiner(d) { return d.join(''); } %}
```

Works like a charm for now. Thanks.

**Comment by Hardmath123** [comment] 2016-05-14 03:50
Glad to hear it!

**Comment by kasbah** [comment] 2017-08-31 15:55
The [docs mention](https://nearley.js.org/docs/grammar) these as "builtins" but not how to include them. I can't seem to use them in my own grammar without defining my own.

**Comment by seiyria** [comment] 2017-08-31 16:00
They don't exist, is why. You have to add them yourself.

**Comment by kasbah** [comment] 2017-08-31 16:10
Ok, so either the docs need to be fixed or the `nuller` needs to be added. Happy to send a PR for either just let me know which one would be preferred.

**Comment by tjvr** [comment] 2017-08-31 19:19
So we have the following "builtins":

- `id`, which is emitted by `generate.js` for js/coffeescript/typescript:

    ```js
    output += "function id(x) { return x[0]; }\n";
    ```

- `joiner`, `arrconcat`, `arrpush`, and `nuller`, which are used internally (e.g. by the EBNF modifiers), by passing e.g. `postprocessor: {builtin: 'nuller'}` to a rule.

    ```js
    generate.javascript.builtinPostprocessors = {
        "joiner": "function joiner(d) {return d.join('');}",
        "arrconcat": "function arrconcat(d) {return [d[0]].concat(d[1]);}",
        "arrpush": "function arrpush(d) {return d[0].concat([d[1]]);}",
        "nuller": "function(d) {return null;}",
        "id": "id"
    ```

I don't think any of the latter are accessible from within a nearley
grammar. You could perhaps write `{% {builtin: 'nuller'} %}`, but I don't think
that counts as working as intended!

@Hardmath123 What would you like to do here? Amend the docs; include all of the
built-in postprocessors in every generated grammar; or come up with a
scheme for detecting which postprocessors are used?

I should note that as discussed elsewhere, we want to discourage use of
`arrconcat` and `arrpush` (because of icky complexity reasons).

**Comment by tjvr** [comment] 2017-08-31 19:20
nb. I added a couple of builtin tests in 4826851.

**Comment by Hardmath123** [comment] 2017-08-31 20:23
We should amend the docs to remove mention of everything except `id`. Then we should go and make `builtins/postprocessors.ne` not suck, and finally document _that_.

**Comment by pcr910303** [comment] 2019-06-18 03:09
@kach Well, this issue is still not being resolved :-(
I just read the generated JS, found out `nuller` isn't defined, added one, but... the docs really should be fixed.

**Closed** 2019-10-04 06:03 UTC
Labels: bug, question
