### ISSUE TITLE
nomnom@1.6.2 no longer supported

### ISSUE THREAD

**Issue by ssilk** [kach/nearley#353] opened 2018-02-20 19:45 UTC

**Comment by ssilk** [comment] 2018-02-20 19:50
https://www.npmjs.com/package/nomnom

**Comment by tjvr** [comment] 2018-02-21 08:51
Duplicate of #352. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Closed** 2018-02-21 08:52 UTC
